/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar for "Internal" Module
  internalSidebar: [
    {
      type: 'category',
      label: 'Internal System',
      link: {
        type: 'generated-index',
        description: 'Dokumentasi Sistem Internal RailFinance',
      },
      collapsed: false,
      items: [
        { type: 'category', label: 'Anggaran', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/anggaran' }] },
        { type: 'category', label: 'Keuangan', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/keuangan' }] },
        { type: 'category', label: 'Manager Keuangan', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/manager-keuangan' }] },
        { type: 'category', label: 'Pajak & Keuangan', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/pajak-keuangan' }] },
        { type: 'category', label: 'Unit Atasan', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/unit-atasan' }] },
        { type: 'category', label: 'Unit Pengaju', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/unit-pengaju' }] },
      ],
    },
  ],

  // Sidebar for "External" Module
  externalSidebar: [
    {
      type: 'category',
      label: 'External System',
      items: [
        'external/external',
        {
          type: 'category',
          label: 'Anggaran',
          items: [
            'external/anggaran/index',
            'external/anggaran/pengajuan-dana',
            'external/anggaran/verifikasi-pendanaan',
          ],
        },
        {
          type: 'category',
          label: 'Keuangan',
          items: [
            'external/keuangan/keuangan-external',
            'external/keuangan/pengajuan-dana',
            'external/keuangan/pembayaran',
          ],
        },
        {
          type: 'category',
          label: 'Manager Keuangan',
          items: [
            'external/manager-keuangan/index',
            'external/manager-keuangan/pengajuan-dana',
            'external/manager-keuangan/pembayaran',
          ],
        },
        {
          type: 'category',
          label: 'Pajak & Keuangan',
          items: [
            'external/pajak-keuangan/index',
            'external/pajak-keuangan/pengajuan-dana',
            'external/pajak-keuangan/pembayaran',
            'external/pajak-keuangan/verifikasi-pendanaan',
            'external/pajak-keuangan/verifikasi-kontrak',
          ],
        },
        {
          type: 'category',
          label: 'Unit Atasan',
          items: [
            'external/unit-atasan/unit-atasan-external',
            'external/unit-atasan/pembayaran-unit-atasan',
            'external/unit-atasan/verifikasi-pendanaan-unit-atasan',
          ],
        },
        {
          type: 'category',
          label: 'Unit Pengaju',
          items: [
            'external/unit-pengaju/unit-pengaju-external',
            'external/unit-pengaju/pembayaran-unit-pengaju',
            'external/unit-pengaju/verifikasi-pendanaan-unit-pengaju',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
