/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar for "Internal" Module
  internalSidebar: [
    {
      type: 'category',
      label: 'Internal System',
      link: {
        type: 'generated-index',
        description: 'Dokumentasi Sistem Internal RailFinance',
      },
      collapsed: false,
      items: [
        { type: 'category', label: 'Anggaran', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/anggaran' }] },
        { type: 'category', label: 'Keuangan', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/keuangan' }] },
        { type: 'category', label: 'Manager Keuangan', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/manager-keuangan' }] },
        { type: 'category', label: 'Pajak & Keuangan', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/pajak-keuangan' }] },
        { type: 'category', label: 'Unit Atasan', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/unit-atasan' }] },
        { type: 'category', label: 'Unit Pengaju', collapsed: true, items: [{ type: 'autogenerated', dirName: 'internal/unit-pengaju' }] }
      ],
    },
  ],

  // Sidebar for "External" Module
  externalSidebar: [
    {
      type: 'category',
      label: 'External System',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'external' }
      ],
    },
  ],
};

module.exports = sidebars;
